site_name: roundup
site_description: roundup is a node based component development tool for JavaScript templating engines.

docs_dir: jsdoc

extra_css:
  - extra.css

repo_name: mgrsskls/roundup
repo_url: https://github.com/mgrsskls/roundup
edit_uri: ""

theme:
  name: material
  font: false

plugins:
  - search # necessary for search to work
  - minify:
      minify_html: true

markdown_extensions:
  - codehilite:
      guess_lang: false
