site_name: JSDoc
site_description: JSdoc for miyagi, a node based component development tool for JavaScript templating engines.

docs_dir: jsdoc

extra_css:
  - extra.css

repo_name: mgrsskls/miyagi
repo_url: https://github.com/mgrsskls/miyagi
edit_uri: ""

theme:
  name: material
  font: false
  favicon: img/favicon.svg
  logo: img/logo.svg

plugins:
  - search # necessary for search to work
  - minify:
      minify_html: true

markdown_extensions:
  - codehilite:
      guess_lang: false
